//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTracer
{
    using System;
    using System.Collections.Generic;
    using ProjectTracer.Models;
    public partial class Administrator :IUser
    {
        public string Id { get; set; }
        public string Password { get; set; }
        public string InvitationCode { get; set; }
    }
}
