//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTracer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int Document_ID { get; set; }
        public string Description { get; set; }
        public string Project_Id { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
