//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTracer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesProjectTracer : DbContext
    {
        public EntitiesProjectTracer()
            : base("name=EntitiesProjectTracer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Documents> Documents { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<Results> Results { get; set; }
        public virtual DbSet<Steps> Steps { get; set; }
        public virtual DbSet<Teams> Teams { get; set; }
        public virtual DbSet<DeadLines> DeadLines { get; set; }
    }
}
