//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTracer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teams
    {
        public int Team_ID { get; set; }
        public string Senior_Id { get; set; }
        public string Dev1 { get; set; }
        public string Dev2 { get; set; }
        public string Dev3 { get; set; }
        public string Dev4 { get; set; }
        public string Dev5 { get; set; }
        public string Dev6 { get; set; }
    }
}
